### ISSUE TITLE
功能更改建议：能否将帮助/help触发更改关键词

### ISSUE THREAD

**Issue by TsukimoriRin** [WindowsSov8forUs/nonebot-plugin-tsugu-bangdream-bot#1]
安装插件以后输入帮助或者help就是本插件的指令 大大能否给这个帮助触发改个名字 比如说 BanGDream帮助 BanGDreamhelp
由于这个指令经常被使用所以提出这个修改意见

**Comment by WindowsSov8forUs** [comment]
> 安装插件以后输入帮助或者help就是本插件的指令 大大能否给这个帮助触发改个名字 比如说 BanGDream帮助 BanGDreamhelp 由于这个指令经常被使用所以提出这个修改意见

是否使用了 nonebot 中其他的 help 插件（如 treehelp ），或是自行实现的 help 功能？

**Comment by TsukimoriRin** [comment]
并没有使用任何help插件

**Comment by WindowsSov8forUs** [comment]
> 并没有使用任何help插件

保留 help 指令头以及对单个指令名称的 help 功能，但是不再对空指令（即 `/help` ）或无法找到的指令名称进行响应，也不在此情况下进行阻塞，这样修改是否可以接受？

**Comment by TsukimoriRin** [comment]
> > 并没有使用任何help插件
> 
> 保留 help 指令头以及对单个指令名称的 help 功能，但是不再对空指令（即 `/help` ）或无法找到的指令名称进行响应，也不在此情况下进行阻塞，这样修改是否可以接受？

不响应也可以！ 也希望能像我说的用插件名称+help触发help功能

**Comment by hakunomiko** [comment]
> > 并没有使用任何help插件
> 
> 保留 help 指令头以及对单个指令名称的 help 功能，但是不再对空指令（即 `/help` ）或无法找到的指令名称进行响应，也不在此情况下进行阻塞，这样修改是否可以接受？

有在使用treehelp插件，现在的情况是输入帮助或者help的空指令以及输入无法找到的指令名称help/帮助指令不会进行响应，但是输入帮助+指令名（比如帮助+查卡）不会显示这条指令名的帮助而是会显示所有指令的帮助，而如果输入help+指令名（比如help+查卡）会同时跳出这条指令名的帮助和所有指令帮助

**Comment by WindowsSov8forUs** [comment]
> > > 并没有使用任何help插件
> > 
> > 
> > 保留 help 指令头以及对单个指令名称的 help 功能，但是不再对空指令（即 `/help` ）或无法找到的指令名称进行响应，也不在此情况下进行阻塞，这样修改是否可以接受？
> 
> 有在使用treehelp插件，现在的情况是输入帮助或者help的空指令以及输入无法找到的指令名称help/帮助指令不会进行响应，但是输入帮助+指令名（比如帮助+查卡）不会显示这条指令名的帮助而是会显示所有指令的帮助，而如果输入help+指令名（比如help+查卡）会同时跳出这条指令名的帮助和所有指令帮助

这个牵扯到对其他帮助插件的适配了……我毕竟不了解 nonebot 在这方面的生态
