### ISSUE TITLE
[功能建议]发送的指令参数错误后，回复对应指令的使用帮助

### ISSUE THREAD

**Issue by Le7emps** [WindowsSov8forUs/nonebot-plugin-tsugu-bangdream-bot#3]
像官bot茨菇一样
⁧⁧ ("⁧‭ 参数 'sos' 不正确, 其应该符合 'int'
查谱面│查铺面 <songId: int> <difficultyText: 'easy'|'ez'|'normal'|'nm'|'hard'|'hd'|'expert'|'ex'|'special'|'sp' = ex> 
根据曲目ID与难度查询铺面信息
使用示例:
查谱面 1 :返回1号曲的ex难度谱面
查谱面 128 special :返回128号曲的special难度谱面

**Comment by WindowsSov8forUs** [comment]
qq官方bot的tsugu是自己写的处理方式
本插件是基于 `nonebot-plugin-alconna` 编写的，处理方式自然是基于 Alconna 实际实现
我可以问问 rf 能不能实现，但如果不行的话我也没办法

**Comment by Le7emps** [comment]
> qq官方bot的tsugu是自己写的处理方式 本插件是基于 `nonebot-plugin-alconna` 编写的，处理方式自然是基于 Alconna 实际实现 我可以问问 rf 能不能实现，但如果不行的话我也没办法

辛苦了

**Comment by kumoSleeping** [comment]
`nonebot-plugin-tsugu-bangdream-bot` 毕竟旨在复刻 `koishi-plugin-tsugu-bangdream-bot` 原则不涉及实际体验的研究.  
虽然我和 Tsugu 开发者提了这方面, 但成效捉襟见肘.  
最早因为官方 Tsugu QQ 机器人新用户较多, 才会设计这样的思路来照顾新用户, 至于实现可以看下面的片段.
https://github.com/kumoSleeping/tsugu-b3/blob/main/tsugu/__init__.py#L505-L509   
其实就是在最后 head_matched 一下然后输出个 help , 对于 nonebot 的 alc 体系来说自然不能直接这么做, 而且官bot茨菇的代码不那么美观, 也不建议学习.   
如果 WindowsSov8 愿意照顾用户体验并且积极解决此技术难题当然是好事👍.

**Comment by WindowsSov8forUs** [comment]
已更新，现在可以在指令参数错误后返回指令帮助
请更新至 0.4.0 版本
